apiVersion: argoproj.io/v1alpha2
kind: Application
metadata:
  name: APPLICATION_NAME
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: 
    targetRevision: COMMIT_SHA
    path: helm-chart
    helm:
      valuesObject:
        image:
          tag: IMAGE_TAG
        ingress:
          hosts:
            - host: PREVIEW_APP_HOST
          tls:
            - hosts:
                - PREVIEW_APP_HOST
  destination: 
    server: PREVIEW_VCLUSTER
    namespace: PREVIEW_NAMESPACE

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true