apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: APPLICATION_NAME
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: 
    targetRevision: COMMIT_SHA
    path: helm-chart
    helm:
      valuesFile:
      - values-preview.yaml
  destination: 
    server: PREVIEW_VCLUSTER
    namespace: PREVIEW_NAMESPACE

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true