name: delete-pr-preview

# on merge to main from pull request (recommended)
on:
  pull_request:
    types: [closed, unlabeled]
    branches:
      - main

env:
  REPO_NAME: ${{ github.event.repository.name }}
  CLUSTER_NAME: 'k8s-demo-cluster'
  GCP_REGION: 'us-east5'
  GCP_ZONE: 'us-east5-b'
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT }}

jobs:
  delete-pr-preview:
    if: ${{ github.event.action == 'closed' }} || ${{ github.event.label.name == 'preview' }}
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install Loft CLI
        uses: loft-sh/setup-loft@v2
        with:
          version: v3.2.4
          url: ${{ secrets.LOFT_URL }}
          # Specify your Loft access key here
          access-key: ${{ secrets.LOFT_PREVIEW_ACCESS_KEY }}

      - name: Delete Preview vcluster
        run: |
          loft delete vcluster $REPO_NAME-pr-${{ github.event.pull_request.number }} --project preview

      - id: 'gcp-auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v1.1.1
        with:
          workload_identity_provider: ${{ secrets.WIF_POOL }}
          service_account: ${{ secrets.WIF_SA_EMAIL }}

      - id: get-credentials
        uses: google-github-actions/get-gke-credentials@v1.0.2
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.GCP_ZONE }}

      - id: delete-argocd-app
        run: |
          VCLUSTER_URL=${{ secrets.LOFT_URL }}/kubernetes/project/preview/virtualcluster/$REPO_NAME-pr-${{ github.event.pull_request.number }}
          PREVIEW_APP_HOST=$REPO_NAME-pr-${{ github.event.pull_request.number }}.previews.k8s.kurtmadel.com
          yq e -i ".metadata.name = \"$REPO_NAME-pr-${{ github.event.pull_request.number }}\"" argocd/preview-app.yaml
          yq e -i ".spec.source.repoURL = \"https://github.com/km-demos/$REPO_NAME.git\"" argocd/preview-app.yaml
          yq e -i ".spec.source.targetRevision = \"${{ github.sha }}\"" argocd/preview-app.yaml
          yq e -i ".spec.destination.namespace = \"preview-$REPO_NAME\"" argocd/preview-app.yaml
          yq e -i ".spec.destination.server = \"$VCLUSTER_URL\"" argocd/preview-app.yaml
          sed -i "s|IMAGE_REPO|${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}|g" argocd/preview-app.yaml
          sed -i "s/IMAGE_TAG/${SHORT_SHA}/g" argocd/preview-app.yaml
          sed -i "s/PREVIEW_APP_HOST/$PREVIEW_APP_HOST/g" argocd/preview-app.yaml
          more argocd/preview-app.yaml
          kubectl delete -f argocd/preview-app.yaml
     
