name: delete-pr-preview

# on merge to main from pull request (recommended)
on:
  pull_request:
    types: [closed, unlabeled]
    branches:
      - main

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  delete-pr-preview:
    if: (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'preview')) || github.event.label.name == 'preview'
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - id: install-loft-cli
        uses: loft-sh/setup-loft@v2
        with:
          version: v3.2.4
          url: ${{ secrets.LOFT_URL }}
          # Specify your Loft access key here
          access-key: ${{ secrets.LOFT_GITHUB_ACTIONS_ACCESS_KEY }}

      - id: delete-preview-vcluster
        run: |
          loft delete vcluster $REPO_NAME-pr-${{ github.event.pull_request.number }} --project preview

      - id: delete-argocd-app
        run: |
          loft use cluster loft-cluster 
          kubectl delete application $REPO_NAME-pr-${{ github.event.pull_request.number }} -n argocd
     
