name: delete-pr-preview

# on merge to main from pull request (recommended)
on:
  pull_request:
    types: [closed, unlabeled]
    branches:
      - main

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  delete-pr-preview:
    if: ${{ github.event.action == 'closed' }} || ${{ github.event.label.name == 'preview' }}
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install Loft CLI
        uses: loft-sh/setup-loft@v2
        with:
          version: v3.2.4
          url: ${{ secrets.LOFT_URL }}
          # Specify your Loft access key here
          access-key: ${{ secrets.LOFT_PREVIEW_ACCESS_KEY }}

      - name: Delete Preview vcluster
        run: |
          loft delete vcluster $REPO_NAME-pr-${{ github.event.pull_request.number }} --project preview
     
